eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8086
spring:
  zipkin:
    base-url:http:jhh//localhost:94111
  application:
    name: service-feign
feign:
  hystrix:
    enabled:true
